
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-sa
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-role
rules:
  
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]

  
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]

  
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

  
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

  
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-binding
subjects:
  - kind: ServiceAccount
    name: platform-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: platform-role
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      serviceAccountName: platform-sa
      containers:
        - name: api
          image: your-image:latest
          ports:
            - containerPort: 8080
